--==============================================================================
--******************************************************************************
--INDEX
--******************************************************************************
--==============================================================================
--TABLE CREATED
CREATE TABLE members (
    member_id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    gender CHAR(1) NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR2(255) NOT NULL,
    PRIMARY KEY(member_id)
);

--DATA INSERTED FROM LINK PROVIDED

--CHECK ALL THE INDEXES FROM ANY TABLE
SELECT
    index_name,
    index_type,
    visibility,
    status
FROM
    all_indexes
WHERE
    TABLE_NAME = 'MEMBERS';
    
--CREATING INDEX ON SINGLE COLOUMN
CREATE INDEX i_members_last_name
ON members(last_name);

--CHECK ALL THE INDEXES FROM ANY TABLE
SELECT
    index_name,
    index_type,
    visibility,
    status
FROM
    all_indexes
WHERE
    TABLE_NAME = 'MEMBERS';
    
SELECT * FROM members
WHERE last_name = 'Harse';

--ADDING PLAN TO CHECK COST A QUERY
EXPLAIN PLAN FOR
SELECT * FROM members
WHERE last_name = 'Harse';

--LISTING ALL THE PLANS BY CALLING PROCEDURE DBMS_XPLAN.DISPLAY()
SELECT
    PLAN_TABLE_OUTPUT
FROM
    TABLE(DBMS_XPLAN.DISPLAY());
    
--REMOVING INDEX
DROP INDEX i_members_last_name;

--CREATING INDEX ON MULTIPLE COLOUMN
CREATE INDEX i_members_name
ON members(last_name, first_name);

SELECT * 
FROM members
WHERE last_name LIKE 'A%'
    AND first_name LIKE 'M%';
    
    
EXPLAIN PLAN FOR
SELECT * 
FROM members
WHERE last_name LIKE 'A%'
    AND first_name LIKE 'M%';
    
SELECT
    PLAN_TABLE_OUTPUT
FROM
    TABLE(DBMS.XPLAN.DISPLAY());
    
DROP INDEX i_members_name;